# -*- coding: utf-8 -*-
"""run_full_pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""

def run_full_pipeline(video_path):
    tracks = run_tracking(video_path)

    motility = run_motility_inference(
        video_path,
        tracks
    )

    morphology = run_morphology_inference(
        video_path,
        tracks
    )

    return {
        "motility": motility,
        "morphology": morphology
    }

