# -*- coding: utf-8 -*-
"""final_decision

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""

def decide_motility(motility_result):
    """
    motility_result = {
        "PR": float,
        "NP": float,
        "IM": float
    }
    """
    pr = motility_result.get("PR", 0)
    np_ = motility_result.get("NP", 0)

    if pr + np_ >= 40:
        return {
            "status": "Normal",
            "reason": "PR + NP ≥ 40%"
        }
    else:
        return {
            "status": "Abnormal",
            "reason": "PR + NP < 40%"
        }
def decide_morphology(morphology_result):
    """
    morphology_result = {
        "normal": float,
        "abnormal": float
    }
    """
    normal = morphology_result.get("normal", 0)

    if normal >= 4:
        return {
            "status": "Normal",
            "reason": "Normal morphology ≥ 4%"
        }
    else:
        return {
            "status": "Abnormal",
            "reason": "Normal morphology < 4%"
        }
def final_decision(motility_result, morphology_result):
    mot = decide_motility(motility_result)
    mor = decide_morphology(morphology_result)

    if mot["status"] == "Normal" and mor["status"] == "Normal":
        overall = "NORMAL"
    elif mot["status"] == "Abnormal" and mor["status"] == "Abnormal":
        overall = "ABNORMAL"
    else:
        overall = "SUBFERTILE"

    return {
        "motility": mot,
        "morphology": mor,
        "overall_status": overall
    }

