# -*- coding: utf-8 -*-
"""roi_cropper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""

import cv2
import os
import pandas as pd

def crop_morphology_roi(
    video_dir: str,
    tracks_csv: str,
    out_dir: str,
    crop_size: int = 64,
    resize_to: int = 224
):
    os.makedirs(out_dir, exist_ok=True)

    df = pd.read_csv(tracks_csv)

    video_files = [
        f for f in os.listdir(video_dir)
        if f.lower().endswith((".mp4", ".avi", ".mov", ".mkv"))
    ]

    def find_video(name):
        key = os.path.splitext(name)[0].lower()
        for v in video_files:
            if key in v.lower():
                return v
        return None

    best_frames = (
        df.sort_values("signal", ascending=False)
          .groupby("particle")
          .first()
          .reset_index()
    )

    saved = 0

    for video_name, group in best_frames.groupby("video"):
        video_file = find_video(video_name)
        if video_file is None:
            continue

        cap = cv2.VideoCapture(os.path.join(video_dir, video_file))

        needed = set(group["frame"].astype(int))
        frames = {}
        idx = 0

        while True:
            ret, frame = cap.read()
            if not ret:
                break
            if idx in needed:
                frames[idx] = frame.copy()
            idx += 1

        cap.release()

        for _, row in group.iterrows():
            f = int(row["frame"])
            if f not in frames:
                continue

            img = frames[f]
            h, w = img.shape[:2]
            x, y = int(row["x"]), int(row["y"])

            half = crop_size // 2
            x1, x2 = max(0, x-half), min(w, x+half)
            y1, y2 = max(0, y-half), min(h, y+half)

            crop = img[y1:y2, x1:x2]
            if crop.size == 0:
                continue

            crop = cv2.resize(crop, (resize_to, resize_to))
            fname = f"{video_file}_particle{row['particle']}.png"
            cv2.imwrite(os.path.join(out_dir, fname), crop)
            saved += 1

    return {
        "saved": saved,
        "out_dir": out_dir
    }

