# -*- coding: utf-8 -*-
"""batch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""

import cv2
import trackpy as tp
import pandas as pd


def batch_detect_sperm(
    video_path: str,
    diameter=21,
    minmass=500,
    separation=50,
    noise_size=1
) -> pd.DataFrame:
    """
    Batch detection using tp.batch
    Output: DataFrame detections
    """

    cap = cv2.VideoCapture(video_path)
    frames = []

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        frames.append(gray)

    cap.release()

    f = tp.batch(
        frames,
        diameter=diameter,
        minmass=minmass,
        separation=separation,
        noise_size=noise_size,
        invert=True,
        preprocess=True,
        max_iterations=10,
        filter_after=True,
        characterize=True,
        engine="numba"
    )

    return f