# -*- coding: utf-8 -*-
"""drift

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""

import trackpy as tp
import pandas as pd


def correct_drift(
    tracks: pd.DataFrame,
    smoothing=30
) -> pd.DataFrame:
    """
    Compute and subtract drift from trajectories
    """

    drift = tp.compute_drift(tracks, smoothing=smoothing)
    corrected = tp.subtract_drift(tracks, drift)

    return corrected