# -*- coding: utf-8 -*-
"""linking

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""

import trackpy as tp
import pandas as pd


def link_and_filter_tracks(
    detections: pd.DataFrame,
    search_range=10,
    memory=5,
    min_frames=30
) -> pd.DataFrame:
    """
    Link detections into trajectories and filter short tracks
    """

    t = tp.link_df(
        detections,
        search_range=search_range,
        memory=memory
    )

    t_filtered = tp.filter_stubs(t, min_frames)

    return t_filtered