# -*- coding: utf-8 -*-
"""locate

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""

import cv2
import trackpy as tp
import pandas as pd


def locate_sperm_from_video(
    video_path: str,
    diameter=21,
    minmass=500,
    separation=30,
    noise_size=1
) -> pd.DataFrame:
    """
    Apply tp.locate frame-by-frame on a single video
    Output: DataFrame detections
    """

    cap = cv2.VideoCapture(video_path)
    detections = []
    frame_index = 0

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        detected = tp.locate(
            gray,
            diameter=diameter,
            minmass=minmass,
            separation=separation,
            noise_size=noise_size,
            invert=True,
            preprocess=True,
            max_iterations=10,
            filter_after=True,
            characterize=True
        )

        if detected is not None and len(detected) > 0:
            detected["frame"] = frame_index
            detections.append(detected)

        frame_index += 1

    cap.release()

    if detections:
        return pd.concat(detections, ignore_index=True)
    else:
        return pd.DataFrame()