# -*- coding: utf-8 -*-
"""morphology_ops

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""

import cv2
import numpy as np
import re


KERNEL_OPEN  = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3,3))
KERNEL_CLOSE = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5,5))
KERNEL_ERODE = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3,3))


def preprocess_binary(img):
    binary = cv2.adaptiveThreshold(
        img, 255,
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY_INV,
        11, 2
    )

    binary = cv2.erode(binary, KERNEL_ERODE, iterations=1)
    binary = cv2.morphologyEx(binary, cv2.MORPH_OPEN, KERNEL_OPEN)

    return binary


def extract_target_sperm(binary):
    num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(binary)

    h, w = binary.shape
    cx_img, cy_img = w // 2, h // 2

    min_dist = np.inf
    target_label = None

    for i in range(1, num_labels):
        cx, cy = centroids[i]
        dist = np.sqrt((cx - cx_img)**2 + (cy - cy_img)**2)
        if dist < min_dist:
            min_dist = dist
            target_label = i

    if target_label is None:
        return None

    mask = np.zeros_like(binary)
    mask[labels == target_label] = 255

    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    filled = np.zeros_like(mask)
    cv2.drawContours(filled, contours, -1, 255, thickness=-1)

    filled = cv2.morphologyEx(filled, cv2.MORPH_CLOSE, KERNEL_CLOSE)

    final = 255 - filled
    return final

