# -*- coding: utf-8 -*-
"""pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""
from morphology_inference.roi_loader import load_roi_images
from morphology_inference.morphology_ops import preprocess_binary, extract_target_sperm
from morphology_inference.predictor import load_model, predict_morphology_cnn


def run_morphology_inference(img_dir, model_path):
    rois = load_roi_images(img_dir)
    model = load_model(model_path)

    results = []

    for item in rois:
        binary = preprocess_binary(item["image"])
        target = extract_target_sperm(binary)

        if target is None:
            continue

        label, prob = predict_morphology_cnn(model, target)

        results.append({
            "filename": item["filename"],
            "label": label,
            "confidence": float(prob)
        })

    return results
