# -*- coding: utf-8 -*-
"""pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""

from morphology_inference.roi_loader import load_roi_images
from morphology_inference.morphology_ops import preprocess_binary, extract_target_sperm
from morphology_inference.predictor import extract_features, predict_morphology


def run_morphology_inference(img_dir):
    rois = load_roi_images(img_dir)

    results = []

    for item in rois:
        binary = preprocess_binary(item["image"])
        target = extract_target_sperm(binary)

        if target is None:
            continue

        features = extract_features(target)
        label = predict_morphology(features)

        results.append({
            "filename": item["filename"],
            "label": label,
            "features": features
        })

    return results

