# -*- coding: utf-8 -*-
"""predictor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""

import cv2
import numpy as np
import tensorflow as tf

LABEL_MAP = {
    0: "abnormal",
    1: "normal"
}

def load_model(model_path):
    return tf.keras.models.load_model(model_path, compile=False)

def preprocess_for_cnn(binary_img):
    img = cv2.resize(binary_img, (224, 224))
    img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
    img = img.astype(np.float32) / 255.0
    return np.expand_dims(img, axis=0)

def predict_morphology_cnn(model, binary_img, threshold=0.5):
    x = preprocess_for_cnn(binary_img)
    prob = model.predict(x, verbose=0)[0][0]
    label = "normal" if prob >= threshold else "abnormal"
    return label, prob


