# -*- coding: utf-8 -*-
"""predictor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""

import cv2
import numpy as np


def extract_features(binary_img):
    _, binary = cv2.threshold(binary_img, 127, 255, cv2.THRESH_BINARY_INV)

    contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if len(contours) == 0:
        return None

    cnt = max(contours, key=cv2.contourArea)

    area = cv2.contourArea(cnt)
    perimeter = cv2.arcLength(cnt, True)

    x, y, w, h = cv2.boundingRect(cnt)
    aspect_ratio = w / h if h > 0 else 0

    hull = cv2.convexHull(cnt)
    solidity = area / cv2.contourArea(hull) if cv2.contourArea(hull) > 0 else 0

    return {
        "area": area,
        "perimeter": perimeter,
        "aspect_ratio": aspect_ratio,
        "solidity": solidity
    }


def predict_morphology(features):
    if features is None:
        return "unknown"

    if features["solidity"] > 0.85 and 0.5 < features["aspect_ratio"] < 2.0:
        return "normal"
    else:
        return "abnormal"

