# -*- coding: utf-8 -*-
"""roi_loader

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""

import cv2
import os

def load_roi_images(img_dir):
    data = []

    for fname in os.listdir(img_dir):
        if not fname.endswith(".png"):
            continue

        path = os.path.join(img_dir, fname)
        img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        if img is None:
            continue

        data.append({
            "filename": fname,
            "image": img
        })

    return data

