# -*- coding: utf-8 -*-
"""pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""

import os
from .video_normalization import normalize_video
from .grayscale import convert_video_to_grayscale
from .contrast import apply_contrast_stretching


def prepare_video_pipeline(
    input_video_path: str,
    working_dir: str
) -> str:
    """
    Full video preparation pipeline:
    1. Normalize FPS & size
    2. Convert to grayscale
    3. Apply contrast stretching

    Returns:
    - path to final prepared video
    """

    os.makedirs(working_dir, exist_ok=True)

    step1 = os.path.join(working_dir, "step1_normalized.mp4")
    step2 = os.path.join(working_dir, "step2_grayscale.mp4")
    step3 = os.path.join(working_dir, "step3_contrast.mp4")

    normalize_video(input_video_path, step1)
    convert_video_to_grayscale(step1, step2)
    apply_contrast_stretching(step2, step3)

    return step3