# -*- coding: utf-8 -*-
"""normalization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""

import subprocess

TARGET_FPS  = 60
TARGET_SIZE = "512:512"

def normalize_video(
    input_path: str,
    output_path: str,
    fps: int = TARGET_FPS,
    size: str = TARGET_SIZE
):
    """
    Normalize video FPS and resolution using ffmpeg
    Output still in video format
    """
    command = [
        "ffmpeg",
        "-y",
        "-i", input_path,
        "-r", str(fps),
        "-vf", f"scale={size}",
        "-c:v", "libx264",
        "-preset", "slow",
        "-crf", "18",
        output_path
    ]

    subprocess.run(
        command,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.STDOUT
    )